<!-- AGREGAT-22 -->
<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li><a href="#compression-22" data-toggle="tab">Компрессия</a></li>
        <li class="active"><a href="#conversion-22" data-toggle="tab">Конверсия</a></li>
    </ul>
    <div class="tab-content">
        <!--  COMPRESSION-22 -->
        <div class="tab-pane" id="compression-22">
            <div class="accordion" id="accordion1_22">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_22-content1">
                            Давление воздуха из компрессора (PS-180)
                        </a>
                    </div>
                    <div id="accordion1_22-content1" class="accordion-body collapse" >
                        <div id="22VZ_PS180" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_22-content2">
                            Давление воздуха за нагнетателем (P-181)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_22-content2" class="accordion-body collapse">
                        <div id="22VZ_P181" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_22-content3">
                            Температура газа перед турбиной (TS-174)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_22-content3" class="accordion-body collapse">
                        <div id="22VZ_TS174" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_22-content4">
                            Расход ПГ в УКСТ (FC-171)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_22-content4" class="accordion-body collapse">
                        <div id="22NG_F171" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_22-content5">
                            Мощность РД (EA-RD)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_22-content5" class="accordion-body collapse">
                        <div id="22EA_RD" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  CONVERSION-22 -->
        <div class="tab-pane active" id="conversion-22">
            <div class="accordion" id="accordion2_22">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content1">
                            Расход воздуха в смеситель (F-102)
                        </a>
                    </div>
                    <div id="accordion2_22-content1" class="accordion-body collapse" >
                        <div id="22VZ_F102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content2">
                            Давление воздуха в смеситель (P-127A)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_22-content2" class="accordion-body collapse">
                        <div id="22VZ_P127A" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content3">
                            Расход NH3 в смеситель (F-101)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_22-content3" class="accordion-body collapse">
                        <div id="22NH3_F101" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content4">
                            Расход NH3 в РСО (F-106)
                        </a>
                    </div>
                    <div id="accordion2_22-content4" class="accordion-body collapse" >
                        <div id="22NH3_F106" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content5">
                            Расход добавочного воздуха (F-103)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_22-content5" class="accordion-body collapse">
                        <div id="22VZ_F103" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content6">
                            Температура под сетками в КА (TS-102)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_22-content6" class="accordion-body collapse">
                        <div id="22TS102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_22-content7">
                            Расход HNO3 с агрегата (F-105)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_22-content7" class="accordion-body collapse">
                        <div id="22HNO3_F105" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
