<!-- AGREGAT-31 -->
<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li><a href="#compression-31" data-toggle="tab">Компрессия</a></li>
        <li class="active"  ><a href="#conversion-31" data-toggle="tab">Конверсия</a></li>
    </ul>
    <div class="tab-content">
        <!--  COMPRESSION-31 -->
        <div class="tab-pane" id="compression-31">
            <div class="accordion" id="accordion1_31">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content1">
                            Давление воздуха из компрессора (PS-180)
                        </a>
                    </div>
                    <div id="accordion1_31-content1" class="accordion-body collapse" >
                        <div id="31VZ_PS180" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content2">
                            Давление воздуха за нагнетателем (P-181)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content2" class="accordion-body collapse">
                        <div id="31VZ_P181" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content3">
                            Температура газа перед турбиной (TS-174)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content3" class="accordion-body collapse">
                        <div id="31VZ_TS174" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content4">
                            Расход ПГ в УКСТ (FC-171)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content4" class="accordion-body collapse">
                        <div id="31NG_F171" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content5">
                            Мощность РД (EA-RD)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content5" class="accordion-body collapse">
                        <div id="31EA_RD" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  CONVERSION-31 -->
        <div class="tab-pane active" id="conversion-31">
            <div class="accordion" id="accordion2_31">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content1">
                            Расход воздуха в смеситель (F-102)
                        </a>
                    </div>
                    <div id="accordion2_31-content1" class="accordion-body collapse" >
                        <div id="31VZ_F102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content2">
                            Давление воздуха в смеситель (P-127A)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content2" class="accordion-body collapse">
                        <div id="31VZ_P127A" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content3">
                            Расход NH3 в смеситель (F-101)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content3" class="accordion-body collapse">
                        <div id="31NH3_F101" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content4">
                            Расход NH3 в РСО (F-106)
                        </a>
                    </div>
                    <div id="accordion2_31-content4" class="accordion-body collapse" >
                        <div id="31NH3_F106" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content5">
                            Расход добавочного воздуха (F-103)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content5" class="accordion-body collapse">
                        <div id="31VZ_F103" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content6">
                            Температура под сетками в КА (TS-102)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content6" class="accordion-body collapse">
                        <div id="31TS102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content7">
                            Расход HNO3 с агрегата (F-105)
                        </a>
                    </div>
                    <div id="accordion2_31-content7" class="accordion-body collapse" >
                        <div id="31HNO3_F105" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
