<!-- AGREGAT-42 -->
<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li><a href="#compression-42" data-toggle="tab"><?php echo $this->translate('Compression');?></a></li>
        <li class="active"  ><a href="#conversion-42" data-toggle="tab"><?php echo $this->translate('Conversion');?></a></li>
    </ul>
    <div class="tab-content">
        <!--  COMPRESSION-42 -->
        <div class="tab-pane" id="compression-42">
            <div class="accordion" id="accordion1_42">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_42-content1">
                        <?php echo $this->translate('Air pressure from the compressor');?> (PS-180)
                        </a>
                    </div>
                    <div id="accordion1_42-content1" class="accordion-body collapse" >
                        <div id="42VZ_PS180" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_42-content2">
                        <?php echo $this->translate('Air pressure behind the supercharger');?> (P-181)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_42-content2" class="accordion-body collapse">
                        <div id="42VZ_P181" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_42-content3">
                        <?php echo $this->translate('Gas temperature in front of the turbine');?> (TS-174)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_42-content3" class="accordion-body collapse">
                        <div id="42VZ_TS174" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_42-content4">
                        <?php echo $this->translate('Consumption of NG in the UKST');?> (FC-171)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_42-content4" class="accordion-body collapse">
                        <div id="42NG_F171" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_42-content5">
                        <?php echo $this->translate('RD power');?> (EA-RD)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_42-content5" class="accordion-body collapse">
                        <div id="42EA_RD" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  CONVERSION-42 -->
        <div class="tab-pane active" id="conversion-42">
            <div class="accordion" id="accordion2_42">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content1">
                        <?php echo $this->translate('Air flow into the mixer');?> (F-102)
                        </a>
                    </div>
                    <div id="accordion2_42-content1" class="accordion-body collapse" >
                        <div id="42VZ_F102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content2">
                        <?php echo $this->translate('Air pressure in the mixer');?> (P-127A)
                        </a>
                    </div>
                    <!-- stock-container !!!   -->
                    <div id="accordion2_42-content2" class="accordion-body collapse">
                        <div id="42VZ_P127A" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content3">
                        <?php echo $this->translate('NH3 consumption in the mixer');?> (F-101)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_42-content3" class="accordion-body collapse">
                        <div id="42NH3_F101" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content4">
                        <?php echo $this->translate('NH3 consumption in RSO');?> (F-106)
                        </a>
                    </div>
                    <div id="accordion2_42-content4" class="accordion-body collapse" >
                        <div id="42NH3_F106" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content5">
                        <?php echo $this->translate('Additional air consumption');?> (F-103)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_42-content5" class="accordion-body collapse">
                        <div id="42VZ_F103" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content6">
                        <?php echo $this->translate('The temperature under the grids in KA');?> (TS-102)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_42-content6" class="accordion-body collapse">
                        <div id="42TS102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_42-content7">
                        <?php echo $this->translate('Consumption of HNO3 from the unit');?> (F-105)
                        </a>
                    </div>
                    <div id="accordion2_42-content7" class="accordion-body collapse" >
                        <div id="42HNO3_F105" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
