<!-- AGREGAT-31 -->
<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li><a href="#compression-31" data-toggle="tab"><?php echo $this->translate('Compression');?></a></li>
        <li class="active"  ><a href="#conversion-31" data-toggle="tab"><?php echo $this->translate('Conversion');?></a></li>
    </ul>
    <div class="tab-content">
        <!--  COMPRESSION-31 -->
        <div class="tab-pane" id="compression-31">
            <div class="accordion" id="accordion1_31">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content1">
                        <?php echo $this->translate('Air pressure from the compressor');?> (PS-180)
                        </a>
                    </div>
                    <div id="accordion1_31-content1" class="accordion-body collapse" >
                        <div id="31VZ_PS180" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content2">
                        <?php echo $this->translate('Air pressure behind the supercharger');?> (P-181)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content2" class="accordion-body collapse">
                        <div id="31VZ_P181" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content3">
                        <?php echo $this->translate('Gas temperature in front of the turbine');?> (TS-174)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content3" class="accordion-body collapse">
                        <div id="31VZ_TS174" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content4">
                        <?php echo $this->translate('Consumption of NG in the UKST');?> (FC-171)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content4" class="accordion-body collapse">
                        <div id="31NG_F171" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1_31-content5">
                        <?php echo $this->translate('RD power');?> (EA-RD)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1_31-content5" class="accordion-body collapse">
                        <div id="31EA_RD" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  CONVERSION-31 -->
        <div class="tab-pane active" id="conversion-31">
            <div class="accordion" id="accordion2_31">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content1">
                        <?php echo $this->translate('Air flow into the mixer');?> (F-102)
                        </a>
                    </div>
                    <div id="accordion2_31-content1" class="accordion-body collapse" >
                        <div id="31VZ_F102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content2">
                        <?php echo $this->translate('Air pressure in the mixer');?> (P-127A)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content2" class="accordion-body collapse">
                        <div id="31VZ_P127A" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content3">
                        <?php echo $this->translate('NH3 consumption in the mixer');?> (F-101)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content3" class="accordion-body collapse">
                        <div id="31NH3_F101" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content4">
                        <?php echo $this->translate('NH3 consumption in RSO');?> (F-106)
                        </a>
                    </div>
                    <div id="accordion2_31-content4" class="accordion-body collapse" >
                        <div id="31NH3_F106" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content5">
                        <?php echo $this->translate('Additional air consumption');?> (F-103)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content5" class="accordion-body collapse">
                        <div id="31VZ_F103" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content6">
                        <?php echo $this->translate('The temperature under the grids in KA');?> (TS-102)
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion2_31-content6" class="accordion-body collapse">
                        <div id="31TS102" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2_31-content7">
                        <?php echo $this->translate('Consumption of HNO3 from the unit');?> (F-105)
                        </a>
                    </div>
                    <div id="accordion2_31-content7" class="accordion-body collapse" >
                        <div id="31HNO3_F105" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
