<!-- ОЦ-2 -->
<div  class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li class="<?php if ($this->tabActive == 'ammonia-gas') {echo 'active';} ?>"  ><a href="#ammonia-gas" data-toggle="tab"><?php echo $this->translate('Gaseous ammonia');?></a></li>
        <li class="<?php if ($this->tabActive == 'ammonia-liq') {echo 'active';} ?>" ><a href="#ammonia-liq" data-toggle="tab"><?php echo $this->translate('Liquid ammonia');?></a></li>
        <li class="<?php if ($this->tabActive == 'natural-gas') {echo 'active';} ?>" ><a href="#natural-gas" data-toggle="tab"><?php echo $this->translate('Natural gas');?></a></li>
        <li class="<?php if ($this->tabActive == 'par16') {echo 'active';} ?>" ><a href="#par16" data-toggle="tab"><?php echo $this->translate('Par16');?></a></li>
        <li class="<?php if ($this->tabActive == 'sklad') {echo 'active';} ?>" ><a href="#sklad" data-toggle="tab">HNO3 <?php echo $this->translate('Storage');?></a></li>
        <li class="<?php if ($this->tabActive == 'hno3-m9') {echo 'active';} ?>" ><a href="#hno3-m9" data-toggle="tab">HNO3 М9</a></li>
        <li class="<?php if ($this->tabActive == 'voda') {echo 'active';} ?>" ><a href="#voda" data-toggle="tab"><?php echo $this->translate('Water');?></a></li>
    </ul>

    <div class="tab-content">
        <!--  AMMONIA_GAS -->
        <div class="tab-pane <?php if ($this->tabActive == 'ammonia-gas') {echo 'active';} ?>" id="ammonia-gas">
            <div class="accordion" id="accordion1">
                <div class="accordion-group">
                    <div class="accordion-heading "  >
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1-content1">
                        <?php echo $this->translate('Pressure of gaseous NH3');?>
                        </a>
                    </div>
                    <div id="accordion1-content1" class="accordion-body collapse" >
                        <div id="02NH3_P4" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1-content2">
                        <?php echo $this->translate('Temperature of gaseous NH3');?>
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1-content2" class="accordion-body collapse">
                        <div id="02NH3_T4" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1-content3">
                        <?php echo $this->translate('Consumption of gaseous NH3');?>
                        </a>
                    </div>
                    <!-- stock-container    -->
                    <div id="accordion1-content3" class="accordion-body collapse">
                        <div id="02NH3_F4" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  AMMONIA-LIQ -->
        <div class="tab-pane <?php if ($this->tabActive == 'ammonia-liq') {echo 'active';} ?>" id="ammonia-liq">
            <div class="accordion" id="accordion2">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content1">
                        <?php echo $this->translate('Liquid ammonia pressure');?>-1
                        </a>
                    </div>
                    <div id="accordion2-content1" class="accordion-body collapse" >
                        <div id="02JAM_P21_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content2">
                        <?php echo $this->translate('Temperature of liquid ammonia');?>-1
                        </a>
                    </div>
                    <div id="accordion2-content2" class="accordion-body collapse">
                        <div id="02JAM_T21_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content3">
                        <?php echo $this->translate('Consumption of liquid ammonia');?>-1
                        </a>
                    </div>
                    <div id="accordion2-content3" class="accordion-body collapse">
                        <div id="02JAM_F21_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content4">
                        <?php echo $this->translate('Liquid ammonia pressure');?>-2
                        </a>
                    </div>
                    <div id="accordion2-content4" class="accordion-body collapse" >
                        <div id="02JAM_P21_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content5">
                        <?php echo $this->translate('Temperature of liquid ammonia');?>-2
                        </a>
                    </div>
                    <div id="accordion2-content5" class="accordion-body collapse">
                        <div id="02JAM_T21_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content6">
                        <?php echo $this->translate('Consumption of liquid ammonia');?>-2
                        </a>
                    </div>
                    <div id="accordion2-content6" class="accordion-body collapse">
                        <div id="02JAM_F21_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  NATURAL-GAZ -->
        <div class="tab-pane  <?php if ($this->tabActive == 'natural-gas') {echo 'active';} ?>" id="natural-gas">
            <div class="accordion" id="accordion3">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion3-content1">
                        <?php echo $this->translate('NG pressure');?>
                        </a>
                    </div>
                    <div id="accordion3-content1" class="accordion-body collapse" >
                        <div  id="02PGAZ_P5" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion3-content2">
                        <?php echo $this->translate('NG temperature');?>
                        </a>
                    </div>
                    <div id="accordion3-content2" class="accordion-body collapse">
                        <div id="02PGAZ_T16" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion3-content3">
                        <?php echo $this->translate('Consumption of NG');?>
                        </a>
                    </div>
                    <div id="accordion3-content3" class="accordion-body collapse">
                        <div id="02PGAZ_F5" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  PAR16 -->
        <div class="tab-pane <?php if ($this->tabActive == 'par16') {echo 'active';} ?>" id="par16">
            <div class="accordion" id="accordion4">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content1">
                        <?php echo $this->translate('Pressure of Steam16');?>-1
                        </a>
                    </div>
                    <div id="accordion4-content1" class="accordion-body collapse" >
                        <div id="02PAR_P2_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content2">
                        <?php echo $this->translate('Temperature of Steam16');?>-1
                        </a>
                    </div>
                    <div id="accordion4-content2" class="accordion-body collapse">
                        <div id="02PAR_T2_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content3">
                        <?php echo $this->translate('Consumption of Steam16');?>-1
                        </a>
                    </div>
                    <div id="accordion4-content3" class="accordion-body collapse">
                        <div id="02PAR_F2_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content4">
                        <?php echo $this->translate('Pressure of Steam16');?>-2
                        </a>
                    </div>
                    <div id="accordion4-content4" class="accordion-body collapse" >
                        <div id="02PAR_P2_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content5">
                        <?php echo $this->translate('Temperature of Steam16');?>-2
                        </a>
                    </div>
                    <div id="accordion4-content5" class="accordion-body collapse">
                        <div id="02PAR_T2_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content6">
                        <?php echo $this->translate('Consumption of Steam16');?>-2
                        </a>
                    </div>
                    <div id="accordion4-content6" class="accordion-body collapse">
                        <div id="02PAR_F2_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content7">
                        <?php echo $this->translate('Consumption coefficient of Steam16');?>
                        </a>
                    </div>
                    <div id="accordion4-content7" class="accordion-body collapse">
                        <div id="02PARG_KF2" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  SKLAD --> 
        <div class="tab-pane  <?php if ($this->tabActive == 'sklad') {echo 'active';} ?>" id="sklad">
            <div class="accordion" id="accordion5">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content1">
                        <?php echo $this->translate('Storage');?> 1(<?php echo $this->translate('department');?>)
                        </a>
                    </div>
                    <div id="accordion5-content1" class="accordion-body collapse" >
                        <div  id="02SKLAD_01L26" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content2">
                        <?php echo $this->translate('Storage');?> 2(<?php echo $this->translate('department');?>)
                        </a>
                    </div>
                    <div id="accordion5-content2" class="accordion-body collapse">
                        <div id="02SKLAD_02L26" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content3">
                        <?php echo $this->translate('Storage');?> 1+2(<?php echo $this->translate('department');?>)
                        </a>
                    </div>
                    <div id="accordion5-content3" class="accordion-body collapse">
                        <div id="02SKLAD_SUM" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content5">
                        <?php echo $this->translate('HNO3 7 AGRs');?>
                        </a>
                    </div>
                    <div id="accordion5-content5" class="accordion-body collapse">
                        <div id="02AK_V_7AGR" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content4">
                        <?php echo $this->translate('HNO3 7 AGRs');?>
                        </a>
                    </div>
                    <div id="accordion5-content4" class="accordion-body collapse">
                        <div id="02HNO3_7AGR" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  HNO3-M9 -->
        <div class="tab-pane  <?php if ($this->tabActive == 'hno3-m9') {echo 'active';} ?>" id="hno3-m9">
            <div class="accordion" id="accordion6">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content1">
                        <?php echo $this->translate('HNO3 consumption output to');?> М9-1(m3/h)
                        </a>
                    </div>
                    <div id="accordion6-content1" class="accordion-body collapse">
                        <div id="02HNO3_F20_1_FV" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content2">
                        <?php echo $this->translate('HNO3 consumption output to');?> М9-1(t/h)
                        </a>
                    </div>
                    <div id="accordion6-content2" class="accordion-body collapse" >
                        <div  id="02HNO3_F20_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content3">
                        <?php echo $this->translate('The concentration of HNO3 on');?> М9-1
                        </a>
                    </div>
                    <div id="accordion6-content3" class="accordion-body collapse" >
                        <div  id="02Q20_1_M9" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content4">
                        <?php echo $this->translate('HNO3 consumption output to');?> М9-2(m3/h)
                        </a>
                    </div>
                    <div id="accordion6-content4" class="accordion-body collapse">
                        <div id="02HNO3_F20_2_FV" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content5">
                        <?php echo $this->translate('HNO3 consumption output to');?> М9-2(t/h)
                        </a>
                    </div>
                    <div id="accordion6-content5" class="accordion-body collapse">
                        <div id="02HNO3_F20_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content6">
                        <?php echo $this->translate('The concentration of HNO3 on');?> М9-2
                        </a>
                    </div>
                    <div id="accordion6-content6" class="accordion-body collapse" >
                        <div  id="02Q20_2_M9" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <!--------------------------->
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content7">
                        <?php echo $this->translate('HNO3 pressure in store');?>-1
                        </a>
                    </div>
                    <div id="accordion6-content7" class="accordion-body collapse">
                        <div id="02HNO3_P20_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content8">
                        <?php echo $this->translate('HNO3 pressure in store');?>-2
                        </a>
                    </div>
                    <div id="accordion6-content8" class="accordion-body collapse">
                        <div id="02HNO3_P20_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content9">
                        <?php echo $this->translate('HNO3 pressure on the tower');?>-1
                        </a>
                    </div>
                    <div id="accordion6-content9" class="accordion-body collapse">
                        <div id="02HNO3_P22_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content10">
                        <?php echo $this->translate('HNO3 pressure on the tower');?>-2
                        </a>
                    </div>
                    <div id="accordion6-content10" class="accordion-body collapse">
                        <div id="02HNO3_P22_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content11">
                        <?php echo $this->translate('The concentration of HNO3 on store');?>
                        </a>
                    </div>
                    <div id="accordion6-content11" class="accordion-body collapse">
                        <div id="02HNO3_Q20" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content12">
                        <?php echo $this->translate('HNO3 temperature in store');?>
                        </a>
                    </div>
                    <div id="accordion6-content12" class="accordion-body collapse">
                        <div id="02HNO3_T20" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  VODA -->
        <div class="tab-pane  <?php if ($this->tabActive == 'voda') {echo 'active';} ?>" id="voda">
            <div class="accordion" id="accordion7">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content1">
                        <?php echo $this->translate('Pressure of XOB');?>
                        </a>
                    </div>
                    <div id="accordion7-content1" class="accordion-body collapse" >
                        <div  id="02XOB_P4" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content2">
                        <?php echo $this->translate('Temperature of XOB');?>
                        </a>
                    </div>
                    <div id="accordion7-content2" class="accordion-body collapse">
                        <div id="02XOB_T1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content3">
                        <?php echo $this->translate('Consumption of XOB');?>
                        </a>
                    </div>
                    <div id="accordion7-content3" class="accordion-body collapse">
                        <div id="02XOB_F1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content4">
                        <?php echo $this->translate('Temperature of OB');?>-1
                        </a>
                    </div>
                    <div id="accordion7-content4" class="accordion-body collapse">
                        <div id="02OB_T1_1" class="accordion-inner">

                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <center><span class="tag-value text-success" ></span></center>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content5">
                        <?php echo $this->translate('Temperature of OB');?>-2
                        </a>
                    </div>
                    <div id="accordion7-content5" class="accordion-body collapse">
                        <div id="02OB_T1_2" class="accordion-inner">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
