<!--<div id="slider-banners" class="carousel slide" style="width: 808px;">    
    <div class="carousel-inner">
        <div class="item active">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/1.jpg" ?>" alt="">
            <div class="carousel-caption">
                <h4>Цех М5 (отделение 1)</h4> 
                <p>Газотурбинные установки ГТТ-3М</p>
            </div>
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/2.jpg" ?>" alt="">
            <div class="carousel-caption">
                <h4>Цех М5 (отделение 1)</h4>
                <p>Газотурбинные установки ГТТ-3М</p>
            </div>
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/3.jpg" ?>" alt="">
            <div class="carousel-caption">
                <h4>Цех М5 (отделение 2)</h4>
                <p>Общий вид цеха М5 (отделение 2) со стороны первого отделения</p>
            </div>
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/4.jpg" ?>" alt="">
            <div class="carousel-caption">
                <h4>Цех М5 (отделение 2)</h4>
                <p>Общий вид цеха М5 (отделение 2) со стороны естокады второго отделения</p>
            </div>
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/5.jpg" ?>" alt="">
            <div class="carousel-caption">
                <h4>Цех М5 (отделение 1)</h4>
                <p>Общий вид цеха М5 (отделение 1) со стороны второго отделения</p>
            </div>
        </div>

    </div>
    <a class="left carousel-control" href="#" data-slide="prev">‹</a>
    <a class="right carousel-control" href="#" data-slide="next">›</a>
</div>-->

<div class="flexslider">
    <ul class="slides">
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/1.jpg"; ?>" alt="" title="Цех М5 (<?php echo $this->translate('department');?> 1) <?php echo $this->translate('Gas turbine installations');?> ГТТ-3М" > </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/2.jpg"; ?>" alt="" title="Цех М5 (<?php echo $this->translate('department');?> 1) <?php echo $this->translate('Gas turbine installations');?> ГТТ-3М"> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/3.jpg"; ?>" alt="" title='Цех М5 (<?php echo $this->translate('department');?> 2) <?php echo $this->translate('Workshop view 1');?>'> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/4.jpg"; ?>" alt="" title='Цех М5 (<?php echo $this->translate('department');?> 2) <?php echo $this->translate('Workshop view 2');?>'> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/about-history/5.jpg"; ?>" alt="" title='Цех М5 (<?php echo $this->translate('department');?> 1) <?php echo $this->translate('Workshop view 3');?>'> </li>
    </ul>
</div>