<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Служба</th>
            <th>Должность</th>
            <th>ФИО</th>
            <th>Раб. телефон</th>
            <th>Моб. телефон</th>
            <th>Эл. адрес</th>
        </tr>
    </thead>
    <tbody>
        <tr class="error">
            <td>Технологическая</td>
            <td>Нач. цеха</td>
            <td>Литошенко Владислав Сергеевич</td>
            <td>39-39-39</td>
            <td>(067)47-40-864</td>
            <td>m5@azot.cherkassy.net</td>
        </tr>
        <tr class="warning">
            <td>Технологическая</td>
            <td>Зам нач. цеха</td>
            <td>Гордиенко Виталий Гаврилович</td>
            <td>39-39-39</td>
            <td>(067)11-11-111</td>
            <td>m5-technolog@azot.cherkassy.net</td>
        </tr>
        <tr class="info">
            <td>КИПиА и АСУ ТП</td>
            <td>Нач. службы</td>
            <td>Симонов Юрий Алексеевич</td>
            <td>39-39-39</td>
            <td>(067)47-40-864</td>
            <td>m5-simonov@azot.cherkassy.net</td>
        </tr>
    </tbody>
</table>
