<div class="media">
    <div class="flowplayer is-splash play-button pull-left" data-ratio="0.4167" data-swf="<?php echo $this->basePath() . '/js/video-players/flowplayer-html5/flowplayer.swf' ?>" >
        <video preload="none">
            <source type="video/mp4"  src="<?php echo $this->basePath() . '/upload/video/M5_40_years.mp4' ?> ">
        </video>
    </div>
    <div class="media-body">
        <h4 class="media-heading text-success" >Цеху азотной кислоты 40 лет</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>
<div class="media">
    <div class="flowplayer is-splash play-button pull-left" data-ratio="0.4167" data-swf="<?php echo $this->basePath() . '/js/video-players/flowplayer-html5/flowplayer.swf' ?>">
        <video preload="none">
            <source type="video/mp4"  src="http://stream.flowplayer.org/bauhaus/624x260.mp4">
        </video>
    </div>
    <div class="media-body">
        <h4 class="media-heading text-success">Тестовое видео</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>
