<div class="media">
    <a href="<?php echo $this->basePath() . '/upload/video/M5_40_years.mp4' ?>" class="divbox-media pull-left" style="background-image:url(<?php echo $this->basePath() . '/img/media/128x128/file-mp4.png' ?>);"><img src="<?php echo $this->basePath() . '/img/media/play.png' ?>"/></a>
    <div class="media-body">
        <h4 class="media-heading text-success" >Цеху азотной кислоты 40 лет</h4>
        Цеху азотной кислоты уже 40 лет. Как быстро летит время...
    </div>
</div>
<!--<div class="media">
    <a href="<?php echo $this->basePath() . '/upload/video/flowplayer.flv' ?>" class="divbox-media pull-left" style="background-image:url(<?php echo $this->basePath() . '/img/media/128x128/file-flv.png' ?>);"><img src="<?php echo $this->basePath() . '/img/media/play.png' ?>"/></a>
    <div class="media-body">
        <h4 class="media-heading text-success">Тестовое видео (flv)</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>
<div class="media">
    <a href="<?php echo $this->basePath() . '/upload/video/InterviewWithGod.swf' ?>" class="divbox-media pull-left" style="background-image:url(<?php echo $this->basePath() . '/img/media/128x128/file-swf.png' ?>);"><img src="<?php echo $this->basePath() . '/img/media/play.png' ?>"/></a>
    <div class="media-body">
        <h4 class="media-heading text-success" >Тестовое видео (swf)</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>
<div class="media">
    <a href="<?php echo $this->basePath() . '/upload/video/NightCity.mp3' ?>" class="divbox-media pull-left" style="background-image:url(<?php echo $this->basePath() . '/img/media/128x128/file-mp3.png' ?>);"><img src="<?php echo $this->basePath() . '/img/media/play.png' ?>"/></a>
    <div class="media-body">
        <h4 class="media-heading text-success">Тестовое видео (mp3)</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>
<div class="media">
    <a href="https://vimeo.com/79902085" class="divbox-media pull-left" style="background-image:url(<?php echo $this->basePath() . '/img/media/128x128/url-vimeo.png' ?>);"><img src="<?php echo $this->basePath() . '/img/media/play.png' ?>"/></a>
    <div class="media-body">
        <h4 class="media-heading text-success" >Тестовое видео (Vimeo video)</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>
<div class="media">
    <a href="http://www.youtube.com/watch?v=hMp_v-I9Z9o" class="divbox-media pull-left" style="background-image:url(<?php echo $this->basePath() . '/img/media/128x128/url-youtube.png' ?>);"><img src="<?php echo $this->basePath() . '/img/media/play.png' ?>"/></a>
    <div class="media-body">
        <h4 class="media-heading text-success">Тестовое видео (Youtube video)</h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>-->
