<!--Set a layout variable-->
<?php
$this->layout()->section = "trends";
$this->layout()->is_highcharts = false;
$this->layout()->is_highstock = true;
$this->layout()->is_asmtrends = true;
$this->layout()->is_utility = true;

//$tags = $this->tags;
?>

<!--Добавим параметры для обьекта класса - AsmTrends-->
<script type="text/javascript">
    addScriptParams('AsmTrends', 
    {
        container: 'asm-trends',
        update_period: 10000, //10 sec
        allowed_number_errors: 3, // допустимое кол. ошибок
        allowable_percentage_out_of_range: 2 // допустимый процент выхода за диапазон от шкалы измерения
    }); 
</script>

<!--Добавим параметры для обьекта класса - ChartBox-->
<script type="text/javascript">
    addScriptParams('ChartBox', 
    {
        StockChart: [
            //======== OC ========//
            // NH3
            {chart : {renderTo: '02NH3_P4',type: 'spline'}},
            {chart : {renderTo: '02NH3_T4',type: 'spline'}},
            {chart : {renderTo: '02NH3_F4',type: 'spline'}},
            // PGAZ
            {chart : {renderTo: '02PGAZ_P5',type: 'spline'}},
            {chart : {renderTo: '02PGAZ_T16',type: 'spline'}},
            {chart : {renderTo: '02PGAZ_F5',type: 'spline'}},
            // JAM-1
            {chart : {renderTo: '02JAM_P21_1',type: 'spline'}},
            {chart : {renderTo: '02JAM_T21_1',type: 'spline'}},
            {chart : {renderTo: '02JAM_F21_1',type: 'spline'}},
            // JAM-2
            {chart : {renderTo: '02JAM_P21_2',type: 'spline'}},
            {chart : {renderTo: '02JAM_T21_2',type: 'spline'}},
            {chart : {renderTo: '02JAM_F21_2',type: 'spline'}},
            // PAR16-1
            {chart : {renderTo: '02PAR_P2_1',type: 'spline'}},
            {chart : {renderTo: '02PAR_T2_1',type: 'spline'}},
            {chart : {renderTo: '02PAR_F2_1',type: 'spline'}},
            // PAR16-2
            {chart : {renderTo: '02PAR_P2_2',type: 'spline'}},
            {chart : {renderTo: '02PAR_T2_2',type: 'spline'}},
            {chart : {renderTo: '02PAR_F2_2',type: 'spline'}},
            // SKLAD
            {chart : {renderTo: '01SKLAD_L26',type: 'spline'}},
            {chart : {renderTo: '02SKLAD_L26',type: 'spline'}},
            {chart : {renderTo: '02SKLAD_SUM',type: 'spline'}},
            // HNO3 M9
            {chart : {renderTo: '02HNO3_F20_1',type: 'spline'}},
            {chart : {renderTo: '02HNO3_F20_2',type: 'spline'}},
            {chart : {renderTo: '02HNO3_P20_1',type: 'spline'}},
            {chart : {renderTo: '02HNO3_P20_2',type: 'spline'}},
            {chart : {renderTo: '02HNO3_P22_1',type: 'spline'}},
            {chart : {renderTo: '02HNO3_P22_2',type: 'spline'}},
            {chart : {renderTo: '02HNO3_Q20',type: 'spline'}},
            {chart : {renderTo: '02HNO3_T20',type: 'spline'}},
            // VODA XOB
            {chart : {renderTo: '02XOB_P4',type: 'spline'}},
            {chart : {renderTo: '02XOB_T1',type: 'spline'}},
            {chart : {renderTo: '02XOB_F1',type: 'spline'}},
            // VODA OB
            {chart : {renderTo: '02OB_T1_1',type: 'spline'}},
            {chart : {renderTo: '02OB_T1_2',type: 'spline'}},
            //============ AGR 1/2 =========//
            //PS-180
            {chart : {renderTo: '12VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '12VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '12VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '12VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '12TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '12VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '12VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '12NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '12NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '12HNO3_F105',type: 'spline'}},
            //============ AGR 2/2 =========//
            //PS-180
            {chart : {renderTo: '22VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '22VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '22VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '22VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '22TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '22VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '22VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '22NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '22NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '22HNO3_F105',type: 'spline'}},
            //============ AGR 3/2 =========//
            //PS-180
            {chart : {renderTo: '32VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '32VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '32VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '32VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '32TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '32VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '32VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '32NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '32NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '32HNO3_F105',type: 'spline'}},
            //============ AGR 4/2 =========//
            //PS-180
            {chart : {renderTo: '42VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '42VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '42VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '42VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '42TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '42VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '42VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '42NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '42NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '42HNO3_F105',type: 'spline'}},
            //============ AGR 5/2 =========//
            //PS-180
            {chart : {renderTo: '52VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '52VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '52VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '52VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '52TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '52VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '52VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '52NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '52NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '52HNO3_F105',type: 'spline'}},
            //============ AGR 6/2 =========//
            //PS-180
            {chart : {renderTo: '62VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '62VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '62VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '62VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '62TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '62VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '62VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '62NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '62NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '62HNO3_F105',type: 'spline'}},
            //============ AGR 7/2 =========//
            //PS-180
            {chart : {renderTo: '72VZ_PS180',type: 'spline'}},
            //P181
            {chart : {renderTo: '72VZ_P181',type: 'spline'}},
            //P127A
            {chart : {renderTo: '72VZ_P127A',type: 'spline'}},
            //TS174
            {chart : {renderTo: '72VZ_TS174',type: 'spline'}},
            //TS102
            {chart : {renderTo: '72TS102',type: 'spline'}},
            //F102
            {chart : {renderTo: '72VZ_F102',type: 'spline'}},
            //F103
            {chart : {renderTo: '72VZ_F103',type: 'spline'}},
            //F101
            {chart : {renderTo: '72NH3_F101',type: 'spline'}},
            //F106
            {chart : {renderTo: '72NH3_F106',type: 'spline'}},
            //F105
            {chart : {renderTo: '72HNO3_F105',type: 'spline'}},
        ]

    });
</script>


<!-- breadcrumbs  -->
<?php echo $this->partial('/asm/asm/lib/charts/breadcrumbs.phtml'); ?>
<!-- content -->
<section id="content">
    <div class="wrapper">
        <div class="box_shadow">
            <div class="box">
                <div class="wrapper">
                    <header class="title">
                        <h2>Данные в реальном времени Цех М-5</h2>
                    </header>

                    <div id="asm-trends" class="tabbable" style="margin-bottom: 18px;">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#oc" data-toggle="tab">ОЦ</a></li>
                            <li class=""><a href="#agregat-1" data-toggle="tab">Агрегат-1/2</a></li>
                            <li class=""><a href="#agregat-2" data-toggle="tab">Агрегат-2/2</a></li>
                            <li class=""><a href="#agregat-3" data-toggle="tab">Агрегат-3/2</a></li>
                            <li class=""><a href="#agregat-4" data-toggle="tab">Агрегат-4/2</a></li>
                            <li class=""><a href="#agregat-5" data-toggle="tab">Агрегат-5/2</a></li>
                            <li class=""><a href="#agregat-6" data-toggle="tab">Агрегат-6/2</a></li>
                            <li class=""><a href="#agregat-7" data-toggle="tab">Агрегат-7/2</a></li>
                        </ul>
                        <div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
                            <!--  OC -->
                            <div class="tab-pane <?php if ($this->navTab == 'oc') {echo 'active';} ?>" id="oc">
                                <!-- ОЦ -->
                                <div  class="tabbable tabs-left">
                                    <ul class="nav nav-tabs">
                                        <li class="<?php if ($this->tabActive == 'ammonia-gas') {echo 'active';} ?>"  ><a href="#ammonia-gas" data-toggle="tab">Газообразный аммиак</a></li>
                                        <li class="<?php if ($this->tabActive == 'ammonia-liq') {echo 'active';} ?>" ><a href="#ammonia-liq" data-toggle="tab">Жидкий аммиак</a></li>
                                        <li class="<?php if ($this->tabActive == 'natural-gas') {echo 'active';} ?>" ><a href="#natural-gas" data-toggle="tab">Природный газ</a></li>
                                        <li class="<?php if ($this->tabActive == 'par16') {echo 'active';} ?>" ><a href="#par16" data-toggle="tab">Пар16</a></li>
                                        <li class="<?php if ($this->tabActive == 'sklad') {echo 'active';} ?>" ><a href="#sklad" data-toggle="tab">HNO3 Склад</a></li>
                                        <li class="<?php if ($this->tabActive == 'hno3-m9') {echo 'active';} ?>" ><a href="#hno3-m9" data-toggle="tab">HNO3 М9</a></li>
                                        <li class="<?php if ($this->tabActive == 'voda') {echo 'active';} ?>" ><a href="#voda" data-toggle="tab">Вода</a></li>
                                    </ul>

                                    <div class="tab-content">
                                        <!--  AMMONIA_GAS -->
                                        <div class="tab-pane <?php if ($this->tabActive == 'ammonia-gas') {echo 'active';} ?>" id="ammonia-gas">
                                            <div class="accordion" id="accordion1">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading "  >
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1-content1">
                                                            Давление газ. NH3
                                                        </a>
                                                    </div>
                                                    <div id="accordion1-content1" class="accordion-body collapse" >
                                                        <div id="02NH3_P4" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1-content2">
                                                            Температура газ. NH3
                                                        </a>
                                                    </div>
                                                    <!-- stock-container    -->
                                                    <div id="accordion1-content2" class="accordion-body collapse">
                                                        <div id="02NH3_T4" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion1-content3">
                                                            Расход газ. NH3
                                                        </a>
                                                    </div>
                                                    <!-- stock-container    -->
                                                    <div id="accordion1-content3" class="accordion-body collapse">
                                                        <div id="02NH3_F4" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--  AMMONIA-LIQ -->
                                        <div class="tab-pane <?php if ($this->tabActive == 'ammonia-liq') {echo 'active';} ?>" id="ammonia-liq">
                                            <div class="accordion" id="accordion2">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content1">
                                                            Давление ЖА-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion2-content1" class="accordion-body collapse" >
                                                        <div id="02JAM_P21_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content2">
                                                            Температура ЖА-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion2-content2" class="accordion-body collapse">
                                                        <div id="02JAM_T21_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content3">
                                                            Расход ЖА-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion2-content3" class="accordion-body collapse">
                                                        <div id="02JAM_F21_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content4">
                                                            Давление ЖА-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion2-content4" class="accordion-body collapse" >
                                                        <div id="02JAM_P21_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content5">
                                                            Температура ЖА-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion2-content5" class="accordion-body collapse">
                                                        <div id="02JAM_T21_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion2-content6">
                                                            Расход ЖА-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion2-content6" class="accordion-body collapse">
                                                        <div id="02JAM_F21_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--  NATURAL-GAZ -->
                                        <div class="tab-pane  <?php if ($this->tabActive == 'natural-gas') {echo 'active';} ?>" id="natural-gas">
                                            <div class="accordion" id="accordion3">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion3-content1">
                                                            Давление ПГ
                                                        </a>
                                                    </div>
                                                    <div id="accordion3-content1" class="accordion-body collapse" >
                                                        <div  id="02PGAZ_P5" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion3-content2">
                                                            Температура ПГ
                                                        </a>
                                                    </div>
                                                    <div id="accordion3-content2" class="accordion-body collapse">
                                                        <div id="02PGAZ_T16" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion3-content3">
                                                            Расход ПГ
                                                        </a>
                                                    </div>
                                                    <div id="accordion3-content3" class="accordion-body collapse">
                                                        <div id="02PGAZ_F5" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--  PAR16 -->
                                        <div class="tab-pane <?php if ($this->tabActive == 'par16') {echo 'active';} ?>" id="par16">
                                            <div class="accordion" id="accordion4">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content1">
                                                            Давление ПАР16-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion4-content1" class="accordion-body collapse" >
                                                        <div id="02PAR_P2_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content2">
                                                            Температура ПАР16-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion4-content2" class="accordion-body collapse">
                                                        <div id="02PAR_T2_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content3">
                                                            Расход ПАР16-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion4-content3" class="accordion-body collapse">
                                                        <div id="02PAR_F2_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content4">
                                                            Давление ПАР16-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion4-content4" class="accordion-body collapse" >
                                                        <div id="02PAR_P2_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content5">
                                                            Температура ПАР16-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion4-content5" class="accordion-body collapse">
                                                        <div id="02PAR_T2_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion4-content6">
                                                            Расход ПАР16-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion4-content6" class="accordion-body collapse">
                                                        <div id="02PAR_F2_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--  SKLAD --> 
                                        <div class="tab-pane  <?php if ($this->tabActive == 'sklad') {echo 'active';} ?>" id="sklad">
                                            <div class="accordion" id="accordion5">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content1">
                                                            Склад 1(отделение)
                                                        </a>
                                                    </div>
                                                    <div id="accordion5-content1" class="accordion-body collapse" >
                                                        <div  id="01SKLAD_L26" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content2">
                                                            Склад 2(отделение)
                                                        </a>
                                                    </div>
                                                    <div id="accordion5-content2" class="accordion-body collapse">
                                                        <div id="02SKLAD_L26" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion5-content3">
                                                            Склад 1+2(отделения)
                                                        </a>
                                                    </div>
                                                    <div id="accordion5-content3" class="accordion-body collapse">
                                                        <div id="02SKLAD_SUM" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--  HNO3-M9 -->
                                        <div class="tab-pane  <?php if ($this->tabActive == 'hno3-m9') {echo 'active';} ?>" id="hno3-m9">
                                            <div class="accordion" id="accordion6">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content1">
                                                            Расход HNO3 выдача на М9-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion6-content1" class="accordion-body collapse" >
                                                        <div  id="02HNO3_F20_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion6-content2">
                                                            Расход HNO3 выдача на М9-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion6-content2" class="accordion-body collapse">
                                                        <div id="02HNO3_F20_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--  VODA -->
                                        <div class="tab-pane  <?php if ($this->tabActive == 'voda') {echo 'active';} ?>" id="voda">
                                            <div class="accordion" id="accordion7">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content1">
                                                            Давление XOB
                                                        </a>
                                                    </div>
                                                    <div id="accordion7-content1" class="accordion-body collapse" >
                                                        <div  id="02XOB_P4" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content2">
                                                            Температура XOB
                                                        </a>
                                                    </div>
                                                    <div id="accordion7-content2" class="accordion-body collapse">
                                                        <div id="02XOB_T1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content3">
                                                            Расход XOB
                                                        </a>
                                                    </div>
                                                    <div id="accordion7-content3" class="accordion-body collapse">
                                                        <div id="02XOB_F1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content4">
                                                            Температура OB-1
                                                        </a>
                                                    </div>
                                                    <div id="accordion7-content4" class="accordion-body collapse">
                                                        <div id="02OB_T1_1" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <center><span class="tag-value text-success" ></span></center>
                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="" href="#accordion7-content5">
                                                            Температура OB-2
                                                        </a>
                                                    </div>
                                                    <div id="accordion7-content5" class="accordion-body collapse">
                                                        <div id="02OB_T1_2" class="accordion-inner">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-1') {echo 'active';} ?>" id="agregat-1">
                                <p>agregat-1</p>
                                <!-- ОЦ -->

                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-2') {echo 'active';} ?>" id="agregat-2">
                                <p>agregat-2</p>
                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-3') {echo 'active';} ?>" id="agregat-3">
                                <p>agregat-3</p>
                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-4') {echo 'active';} ?>" id="agregat-4">
                                <p>agregat-4</p>
                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-5') {echo 'active';} ?>" id="agregat-5">
                                <p>agregat-5</p>
                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-6') {echo 'active';} ?>" id="agregat-6">
                                <p>agregat-6</p>
                            </div>
                            <div class="tab-pane <?php if ($this->navTab == 'agregat-7') {echo 'active';} ?>" id="agregat-7">
                                <p>agregat-7</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper">
<?php echo $this->partial('/application/index/lib/home/articles-post.phtml'); ?>
    </div>    
</section>
<!-- content -->



