<!--Set a layout variable-->
<?php 
$this->layout()->section = "reports";
?>

<!-- breadcrumbs  -->
<?php echo $this->partial('/asm/asm/lib/reports/breadcrumbs.phtml'); ?>
<!-- content -->
<section id="content">
    <div class="wrapper">
        <div class="box_shadow">
            <div class="box">
                <div class="wrapper">
                    <header class="title">
                        <h2><?php echo $this->translate('Reports');?></h2>
                    </header>
                    <form class="">
                        <fieldset>
                            <legend><?php echo $this->translate('Monthly reports');?></legend>
                            <div class="input-append">
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4"><?php echo $this->translate('HNO3 production');?></span><a href="<?php echo $this->GetReportURL('monthHNO3_M5-html'); ?>" target="_blank" class="btn btn-primary"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('monthHNO3_M5-xls'); ?>" class="btn btn-inverse" ><?php echo $this->translate('Download');?></a><img></img>  </p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4"><?php echo $this->translate('Gas. ammonia on the shop');?></span><a href="<?php echo $this->GetReportURL('monthAllGAM_M5-html'); ?>" target="_blank" class="btn btn-primary"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('monthAllGAM_M5-xls'); ?>" class="btn btn-inverse"><?php echo $this->translate('Download');?></a><img></img></p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4"><?php echo $this->translate('Gas. ammonia by aggregates');?></span><a href="<?php echo $this->GetReportURL('monthAgrGAM_M5-html'); ?>" target="_blank" class="btn btn-primary"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('monthAgrGAM_M5-xls'); ?>" class="btn btn-inverse"><?php echo $this->translate('Download');?></a><img></img></p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4"><?php echo $this->translate('Liquid ammonia');?></span><a href="<?php echo $this->GetReportURL('monthAllJAM_M5-html'); ?>" target="_blank" class="btn btn-primary"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('monthAllJAM_M5-xls'); ?>" class="btn btn-inverse"><?php echo $this->translate('Download');?></a><img></img></p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4"><?php echo $this->translate('Consumption coefficients');?></span><a href="<?php echo $this->GetReportURL('monthRashodK_M5-html'); ?>" target="_blank" class="btn btn-primary"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('monthRashodK_M5-xls'); ?>" class="btn btn-inverse"><?php echo $this->translate('Download');?></a><img></img></p>
                            </div>
                        </fieldset>
                    </form>

                    <form class="">
                        <fieldset>
                            <legend><?php echo $this->translate('Daily reports');?></legend>
                            <div class="input-append">
                                <p><input class="report-check" type="checkbox" value="" checked><span class="uneditable-input span4">М5-2 <?php echo $this->translate('Resources consumed');?></span><a href="<?php echo $this->GetReportURL('dailyResourcesM5_2-html'); ?>" class="btn btn-primary" target="_blank"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailyResourcesM5_2-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                                <p><input class="report-check" type="checkbox" value="" checked><span class="uneditable-input span4">М5-2 <?php echo $this->translate('Development for accounting');?></span><a href="<?php echo $this->GetReportURL('dailyProductionM5_2-html'); ?>" class="btn btn-primary" target="_blank"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailyProductionM5_2-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                                <p><input class="report-check" type="checkbox" value="" checked><span class="uneditable-input span4">М5-2 <?php echo $this->translate('PG Parameters');?></span><a href="<?php echo $this->GetReportURL('dailyNGParamsM5_2-html'); ?>" class="btn btn-primary" target="_blank"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailyNGParamsM5_2-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                                <p><input class="report-check" type="checkbox" value="" checked><span class="uneditable-input span4">М5-1 <?php echo $this->translate('Average values for accounting');?></span><a href="<?php echo $this->GetReportURL('dailyAvgM5_1-html'); ?>" target="_blank" class="btn btn-primary"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailyAvgM5_1-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4">М5-1 (<?php echo $this->translate('Total values');?>)</span><a href="<?php echo $this->GetReportURL('dailySumM5_1-html'); ?>" class="btn btn-primary" target="_blank"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailySumM5_1-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4">М7-2 (<?php echo $this->translate('Total values');?>)</span><a href="<?php echo $this->GetReportURL('dailySumM7_2-html'); ?>" class="btn btn-primary" target="_blank"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailySumM7_2-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                                <p><input class="report-check" type="checkbox" value=""><span class="uneditable-input span4">М7-1 (<?php echo $this->translate('Total values');?>)</span><a href="<?php echo $this->GetReportURL('dailySumM7_1-html'); ?>" class="btn btn-primary" target="_blank"><?php echo $this->translate('Open');?></a><a href="<?php echo $this->GetReportURL('dailySumM7_1-html'); ?>" class="btn btn-inverse print-this"><?php echo $this->translate('Print');?></a><img src="<?php echo $this->basePath() . '/img/system/loading.gif' ?> " class="wait-loading-data" /></p>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper">
        <?php echo $this->partial('/application/index/lib/home/articles-post.phtml'); ?>
    </div>    
</section>
<!-- content -->



