
<header>
    <h1>Название сайта</h1>
</header>
<!-- navbar-inverse   -->
<div class="navbar ">
    <nav class="navbar-inner">
        <a class="brand" href="#">Название проекта</a>
        <ul class="nav">
            <li class="divider-vertical"></li>
            <li><a href="#"><i class="icon-home"></i> Страница</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Страница <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Страница 2</a></li>
                    <li><a href="#">Страница 2</a></li>
                    <li><a href="#">Страница 2</a></li>
                    <li class="dropdown-submenu">
                        <a href="#">Страница 2</a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Страница 3</a></li>
                            <li><a href="#">Страница 3</a></li>
                            <li><a href="#">Страница 3</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="#">Страница</a></li>
            <li><a href="#">Страница</a></li>
            <li><a href="#">Страница</a></li>
        </ul>
        <form class="navbar-form pull-right ">
<!--                <input type="text" class="span2" />
            <button type="submit" class="btn">Поиск</button>-->
            <input type="text" class="span2 search-query" placeholder="Ввести запрос" />
        </form>
    </nav>
</div>
<div class="row ">
    <div class="carousel slide span5 offset3" id="my-carousel">
        <ol class="carousel-indicators">
            <li class="active" data-target="#my-carousel" data-slide-to="0"></li>
            <li data-target="#my-carousel" data-slide-to="1"></li>
            <li data-target="#my-carousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="item active">
                <img src="<?php echo $this->basePath() . '/img/carousel/1.jpg' ?>" />
                <!--                    <div class="carousel-caption" >
                                        <h4>Заголовок слайда 1</h4>
                                        <p>Описание слайда 1</p>
                                    </div>-->
            </div>
            <div class="item">
                <img src="<?php echo $this->basePath() . '/img/carousel/2.jpg' ?>" />
                <!--                    <div class="carousel-caption">
                                        <h4>Заголовок слайда 2</h4>
                                        <p>Описание слайда 3</p>
                                    </div>-->
            </div>
            <div class="item">
                <img src="<?php echo $this->basePath() . '/img/carousel/3.jpg' ?>" />
                <!--                    <div class="carousel-caption">
                                        <h4>Заголовок слайда 3</h4>
                                        <p>Описание слайда 3</p>
                                    </div>-->
            </div>
        </div>
        <a class="carousel-control left" data-slide="prev" href="#my-carousel">&lsaquo;</a>
        <a class="carousel-control right" data-slide="next" href="#my-carousel">&rsaquo;</a>
    </div>
</div>
<article class="row">
    <p class="span4">Любой текст, какой прийдет в вашу светлую голову!</p>
    <p class="span4">Любой текст, какой прийдет в вашу светлую голову!</p>
    <p class="span4">Любой текст, какой прийдет в вашу светлую голову!</p>
</article>



