<!--Общие данные для передачи в JavaScript-->
<div class="msg-box" style="display: none">
    <!--Базовый путь к ресурсам-->
    <p id="urlBase"><?php echo $this->basePath()?></p>
    <p id="language">ru</p>
    <p id="msgImage"><?php echo $this->translate("Image")?></p>
    <p id="msgOf"><?php echo $this->translate("from")?></p>
    <p id="msgDisplayInNewWindow"><?php echo $this->translate("View in a separate window")?></p>
    <p id="msgTitleInformation"><?php echo $this->translate("Information")?></p>
    <p id="msgDetails"><?php echo $this->translate("Read more...")?></p>
    <p id="msgCancel"><?php echo $this->translate("Cancel")?></p>
    <p id="msgPlay"><?php echo $this->translate("Play")?></p>
    <p id="msgStop"><?php echo $this->translate("Stop")?></p>
    
    <!--Виды сообщений -->
    <p id="alert-block"><?php echo $this->translate("alert-block")?></p>
    <p id="alert-error"><?php echo $this->translate("alert-error")?></p>
    <p id="alert-success"><?php echo $this->translate("alert-success")?></p>
    <p id="alert-info"><?php echo $this->translate("alert-info")?></p>
    
    <p id="msgSaving"><?php echo $this->translate("Saving")?></p>
    <p id="msgClickToEdit"><?php echo $this->translate("Click the mouse to edit")?></p>
    <p id="msgLoadingMessages"><?php echo $this->translate("Loading messages...")?></p>
    <p id="msgIsPreparingReport"><?php echo $this->translate("Is preparing a report ...")?></p>
    <p id="msgAlreadyPassed"><?php echo $this->translate("Already passed")?></p>
    <p id="msgMinutes"><?php echo $this->translate("min.")?></p>
    <p id="msgSeconds"><?php echo $this->translate("sec.")?></p>
    <p id="msgInput"><?php echo $this->translate("Input")?></p>
    <p id="msgErrNoAccessToInformationResources"><?php echo $this->translate('Not have access to relevant information resources - "{info_res}"')?></p>
    <p id="msgOrHere"><?php echo $this->translate("or here")?></p>
    <p id="msgOr"><?php echo $this->translate("or")?></p>
    <p id="msgHere"><?php echo $this->translate("here")?></p>
    <p id="msgСlean"><?php echo $this->translate("Clear")?>Очистить</p>
    <p id="msgWaitLoadingData"><?php echo $this->translate("Wait! Loading data ...") ?></p>
    <p id="msgFailedGetResourceUrl"><?php echo $this->translate("Failed to get the resource at -  {url}") ?></p>
    
    <p id="msgErrVideo"><?php echo $this->translate("Error video")?></p>
    <p id="msgErrCode"><?php echo $this->translate("Error code")?></p>
    <p id="msgErrMessage"><?php echo $this->translate("Error message")?></p>
    <p id="msgErrPrint"><?php echo $this->translate("Error print")?></p>
    
</div>