<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('Real-time data');?></h2>
        <p><?php echo $this->translate('About Real-time data');?></p>
        <p><a class="btn btn-primary" href="<?php echo $this->basePath() . "/index.php/asm/charts?tab=ammonia-gas" ?>" ><?php echo $this->translate('More detailed');?>... &raquo;</a></p>
    </div>
    <div class="span4">
        <h2><?php echo $this->translate('Reports');?></h2>
        <p><?php echo $this->translate('About Reports');?></p>
        <p><a class="btn btn-primary" href="<?php echo $this->basePath() . "/index.php/asm/reports" ?>" ><?php echo $this->translate('More detailed');?>... &raquo;</a></p>
    </div>
    <div class="span4">
        <h2><?php echo $this->translate('Data collection stations');?></h2>
        <p><?php echo $this->translate('About Data collection stations');?></p>
        <p><a class="btn btn-primary" href="<?php echo $this->basePath() . "/index.php/asm/dcs" ?>" ><?php echo $this->translate('More detailed');?>... &raquo;</a></p>
    </div>
</div>
