<div class="row">
    <div class="span4">
        <h2>Данные в реальном времени</h2>
        <p>Здесь можно посмотреть данные в реальном времени, а также их историю.</p>
        <p><a class="btn btn-primary" href="<?php echo $this->basePath() . "/index.php/asm/charts?tab=ammonia-gas" ?>" >Подробнее... &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>Отчеты</h2>
        <p>Здесь можно посмотреть месячные/суточные отчеты по основным параметрам цеха: производство HNO3, потребление основных ресурсов, расходные коэфициенты и т.д.</p>
        <p><a class="btn btn-primary" href="<?php echo $this->basePath() . "/index.php/asm/reports" ?>" >Подробнее... &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>Станции сбора данных</h2>
        <p>Здесь можно посмотреть текущие данные по основным учетным параметрам цехов. В качестве станций сбора данных используются приборы DX-2000 разработчик "Yokogawa Electric"</p>
        <p><a class="btn btn-primary" href="<?php echo $this->basePath() . "/index.php/asm/dcs" ?>" >Подробнее... &raquo;</a></p>
    </div>
</div>
