<div id="slider-banners" class="carousel slide" style="width: 808px;">    
    <div class="carousel-inner">
        <div class="item  active">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/1.jpg" ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/2.jpg" ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/3.jpg" ?>" alt="">
         </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/4.jpg" ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/5.jpg" ?>" alt="">
         </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/6.jpg" ?>" alt="">
         </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/7.jpg" ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/8.jpg" ?>" alt="">
         </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/9.jpg" ?>" alt="">
         </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/10.jpg" ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/11.jpg" ?>" alt="">
         </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/12.jpg" ?>" alt="">
        </div>
        <div class="item">
            <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-christmas/13.png" ?>" alt="">
         </div>

     </div>
    <a class="left carousel-control" href="#" data-slide="prev">‹</a>
    <a class="right carousel-control" href="#" data-slide="next">›</a>
</div>
