<!-- home-slider-images -->
<div class="flexslider">
    <ul class="slides">
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/01.jpg"; ?>" alt="" title="" > </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/02.jpg"; ?>" alt="" title=""> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/03.jpg"; ?>" alt="" title=""> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/04.jpg"; ?>" alt="" title=""> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/05.jpg"; ?>" alt="" title=""> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/06.jpg"; ?>" alt="" title=""> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/07.jpg"; ?>" alt="" title=""> </li>
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-8-march/08.png"; ?>" alt="" title=""> </li>
    </ul>
</div>