<!-- home-slider-images -->
<div class="flexslider">
    <ul class="slides">
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-main/1.jpg"; ?>" alt="" title="Командно-штабні навчання МНС" > </li>
        <!-- <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-main/2.jpg"; ?>" alt="" title="Цех М-5"> </li> -->
        <li> <img src="<?php echo $this->basePath() . "/upload/img/carousel/home-main/3.jpg"; ?>" alt="" title='<?php echo $this->translate('Cherkassy AZOT');?>'> </li>
    </ul>
</div>